### ISSUE TITLE
VC2019 throws error.

### ISSUE THREAD

**Issue by zBeeble42** [gbresearch/axe#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2386	'parse_tree_result_t': a symbol with this name already exists in the current scope	UnrealTable	C:\Users\foo\Documents\Unreal Projects\AXE\include\axe_composite.h	109	

... so I really like the project... but IDK... sorta blocked here.  It twiggs many buttons that make me happy, tho.

**Comment by gbresearch** [comment]
can't reproduce

**Comment by elijahfhopp** [comment]
@zBeeble42 there seems to be a symbol (a function or class) from the Unreal Engine code that shares the same name as a symbol in axe. Your options are limited here, but you can always rename of that symbol in axe with a refactor.

**Comment by gbresearch** [comment]
All symbols in AXE are in axe namespace. I'm not familiar with the Unreal Engine. Does the Unreal Engine also uses axe namespace? Is there a "using namespace axe" somewhere? Other than that only ADL can find symbols in associated namespaces, but I don't see how that can be happening.

**Comment by elijahfhopp** [comment]
Upon further research, that type doesn't even exist in AXE, namespaced or not, so this is an issue from the OP's code.
