### ISSUE TITLE
convert_iterator doesn't work with const char*

### ISSUE THREAD

**Issue by ivan-tkatchev** [gbresearch/axe#3]
convert_iterator (and e.g., r_ucase and other converting rules) assume that the iterator type is a C++ iterator, and not a const char*.
This means parsing rules expect an std::string or other container, and std::string_view will case a compilation error.

**Comment by ivan-tkatchev** [comment]
I've made a fork with a simple fix.

**Comment by gbresearch** [comment]
fixed in master
